const express = require("express");
const { GoogleGenerativeAI } = require("@google/generative-ai");
const portfolioContext = require("../data/portfolioContext");

const router = express.Router();

const formatHistory = (history = []) => {
  if (!Array.isArray(history) || history.length === 0) return "";

  return history
    .slice(-8)
    .map(([userMessage, assistantMessage]) => {
      return `User: ${userMessage}\nAssistant: ${assistantMessage}`;
    })
    .join("\n\n");
};

const buildSystemPrompt = () => {
  const p = portfolioContext;
  const projectList = p.projects
    .map((proj) => `  - ${proj.title} [${proj.stack.join(", ")}]: ${proj.impact} Live: ${proj.liveUrl} GitHub: ${proj.githubUrl}`)
    .join("\n");
  const expList = p.experience
    .map((e) => `  - ${e.title} at ${e.company} (${e.duration}): ${e.highlights.join("; ")}`)
    .join("\n");

  return `You are the AI assistant for ${p.person.name}'s portfolio website. Speak in first person as ${p.person.shortName}. Be professional, concise, and friendly. Only use the facts below — never invent details.

Formatting rules — strictly follow:
- Use **bold** only for section labels like **LinkedIn:** or project names.
- Write URLs as plain text (e.g. https://example.com), never as markdown links like [text](url).
- Use bullet points (- item) when listing multiple items.
- Keep responses short and scannable — max 5-6 lines unless the user asks for detail.

Person: ${p.person.name} | ${p.person.role} | ${p.person.location}
Email: ${p.person.email} | LinkedIn: ${p.person.linkedin} | GitHub: ${p.person.github} | Codolio: ${p.person.codolio}
Summary: ${p.summary}
Education: ${p.education.degree} at ${p.education.institution} (${p.education.year}) — CGPA ${p.education.cgpa}
Certifications: ${p.certifications.join(", ")}
Skills — Frontend: ${p.skills.frontend.join(", ")} | Backend: ${p.skills.backend.join(", ")} | AI: ${p.skills.ai.join(", ")} | DBs: ${p.skills.databases.join(", ")} | Tools: ${p.skills.tools.join(", ")}
Experience:
${expList}
Projects:
${projectList}`.trim();
};

router.post("/", async (req, res) => {
  const { message, history } = req.body || {};

  if (!message || typeof message !== "string") {
    return res.status(400).json({ error: "Message is required." });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(503).json({ error: "Gemini API key is not configured on server." });
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({
      model: process.env.GEMINI_MODEL || "gemini-2.5-flash",
      generationConfig: {
        temperature: 0.6,
        maxOutputTokens: 800,
      },
    });

    const prompt = [
      buildSystemPrompt(),
      formatHistory(history),
      `User: ${message}`,
      "Assistant:",
    ]
      .filter(Boolean)
      .join("\n\n");

    const result = await model.generateContent(prompt);
    const responseText = result?.response?.text?.()?.trim();

    if (!responseText) {
      return res.status(502).json({ error: "No response generated by Gemini." });
    }

    return res.json({ response: responseText });
  } catch (error) {
    const status = error?.status || 500;

    if (status === 429) {
      const retryAfter = error?.errorDetails?.find?.(
        (d) => d["@type"]?.includes("RetryInfo")
      )?.retryDelay || "60s";
      console.warn(`Gemini rate limit hit. Retry after ${retryAfter}.`);
      return res.status(429).json({
        error: "Rate limit reached. Falling back to local data.",
        retryAfter,
      });
    }

    console.error("Gemini chat route error:", error);
    return res.status(500).json({ error: "Failed to generate response." });
  }
});

module.exports = router;
